redom/redom

- src/curry.js
- src/el.js
- src/mount.js
- src/on.js
- src/text.js
- Add support for `on('event', callback)`, #14 (do we have any other curry functions?)
- Changed `text` to be a function call instead of a bind to allow V8 to inline it.
- Removed `String` and `Number` support from `mount`❗ They are now handled entirely within `expand`, this avoids logic duplication and doing unnecessary work where a text node would be checked for `mount`, child elements, etc. Feel free to object here, although I didn't think `mount(document.body, 'foo')` is something someone would want to do 🤔.
```
Benching REDOM <div> with el()
7686ns per iteration (130107 ops/sec)
Benching REDOM <div> with precached elements
6861ns per iteration (145746 ops/sec)
```
Starting to wonder where we can _remove_ some code...
> More stuff

- dist/doc.md
- src/mount.js
- Removed unnecessary if condition in `doUnmount`. Function already return if `hooks` is false.
- Updated documentation. Renamed lifecycle hooks to match new v2 hook names.
> Removed unnecessary condition and update docs. 

- dist/doc.md
Fixes to the keyed list code examples
> doc.md typos for keyed lists

- src/list.js
- Replaces the conditional checking whether `key` is a function on every iteration, by always making `key` a function
- Amend the `if (key)` checks into `if (key == null)` (request by @pakastin)
> Remove conditional from loop

- src/mount.js
- test/redom.js
- test/test.js
Fix for #90 
Check if `parentEl` contains `childEl` before trying to remove it. Also skips lifecycle hooks if child is not found from DOM.
> Prevent DOMException upon unmounting component that is not mounted yet

- src/parse-query.js
- test/redom.js
Instead of constructing separate buffer string, use substrings from original query string in `parseQuery` function. This could hopefully improve performance of the function.
> Use substrings in query parsing

- esm/mount.js
Using window without checking if it is available broke no:dom
I didn't yet check that are there more places were this should be fixed, but this will make the no:dom Hello World example work again :)
> check window availability before using it

- esm/unmount.js
- test/test.js
This pull request addresses the following issue:
Replacing a child element/component _without lifecycle events, or with the last hook for a given event_ with another element (whether it has or does not have lifecycle events doesn't matter) using `setChildren` causes lifecycle events elsewhere in the document to be forgotten.
**RE:DOM version**: 3.12.4
1. Define a component with `onmount`/`onunmount` lifecycle events
2. Create two instances of the component (henceforth `a` and `b`)
3. Mount instance `a` somewhere
4. Use `setChildren` to assign `a` a child which _does not have lifecycle events_
5. Use `setChildren` to set `b` as `a`'s only child
6. Unmount `a` from its parent
`onunmount` is called twice when `a` is unmounted: once on `a`, and once on `b`.
`onunmount` is never called.
This …
> Ensure lifecycle events are updated correctly during unmount triggered by setChildren

- esm/util.js
Removed more than one `typeof el` check in `util`.
> Made `util` more performant.

- dist/redom.js
- esm/html.js
- esm/listpool.js
- esm/setattr.js
- esm/setstyle.js
- esm/svg.js
- esm/util.js
- test/redom.js
A follow-up to #120, which removes code which checks `typeof x` twice. This should help performance a bit.
> Removed is* type guard functions

- package.json
Added a semistandard ignore deceleration in `package.json`, becuase seeing:
```
/home/def14nt/Desktop/code/Forks/redom/dist/prism.js:6:626: Unexpected use of comma operator.
/home/def14nt/Desktop/code/Forks/redom/dist/prism.js:6:708: Unnecessary escape character: \/.
/home/def14nt/Desktop/code/Forks/redom/dist/prism.js:6:734: Unnecessary escape character: \/.
/home/def14nt/Desktop/code/Forks/redom/dist/prism.js:7:1: Expected an assignment or function call and instead saw an expression.
/home/def14nt/Desktop/code/Forks/redom/dist/prism.js:7:450: Unnecessary escape character: \?.
/home/def14nt/Desktop/code/Forks/redom/dist/prism.js:7:452: Unnecessary escape character: \*.
/home/def14nt/Desktop/code/Forks/redom/dist/prism.js:7:2734: Expected an assignment or function call and instead saw an …
```
> Added a semistandard ignore deceleration

- index.html
The example didn't actually render anything. Adding the mount call means that it does.
> Improved "no need for bundlers" example

- dist/doc.md
The documentation includes the statements `table = el('table', Tr)` instead of `table = list('table', Tr)` in two cases. This commit corrects that.
> Correct list component documentation

- esm/parse-query.js
- test/redom.js
Optimized parseQuery function. Less code and faster. Please see the rough performance test result below.
|iterate|old parseQuery(ms)|new parseQuery(ms)|
|---|---|---|
|10|1|1|
|10^2|6|2|
|10^3|10|7|
|10^4|56|48|
|10^5|534|268|
|10^6|4820|2985|
```
const selectors = ['div.hello.world', 'p#id', 'ul#hello.world', 'footer.footer.top', 'button.button#submitButton', '.usa.world'];
function test1(iterate) {
const initTime = Date.now();
const record = [];
for (let i = 0; i < iterate; i++) {
selectors.forEach(selector => {
record.push(parseQuery(selector));
});
}
const closeTime = Date.now();
console.log(closeTime - initTime, record.length);
}
function test2(iterate) {
const initTime = Date.now();
const record = [];
for (let i = 0; i < iterate; i++) {
selectors.forEach(selector => { …
```
> Optimized parseQuery helper function

- README.md
remove contribute link as [Contribute](https://github.com/redom/redom/blob/master/CONTRIBUTING.md) is not a valid link and the file is not located anywhere in redom project anyways.
> remove contribute link

- esm/parse-query.js
- test/redom.js
When reading the `parseQuery` code I got confused because many checks look unnecessary to me. As far as I can see, it can be simplified to this. Should also be [slightly faster](https://jsperf.com/parsequery/1).
> Simplified parseQuery

- index.d.ts
This is how typescript resolves the types on this pr:
~The only one case not having a nice element resolution is the `aEl`. Reason is, because the this.el definition in the function cannot be recognized by typescript, I previously decided to just fallback to HTMLElement in this case, but I think we should actually change this case to RedomComponent.~
Edit: we removed Function as a valid query argument type so the aEl case has to be typed by the consumer manually.
---
Used code for type testing:
```typescript
import { el } from '.'
class TdComponent {
el = el('td')
}
const els = {
tableEl: el(document.createElement('table')),
tdComponent: el(TdComponent),
divEl: el('div'),
aEl: el(function() {
this.el = el('a')
}),
buttonEl: el(function() {
return {
el: el('button')
} 
}),
inputEl: …
```
> [BUGFIX] Fix el fn query argument type and update corresponding return type

- index.d.ts
Current workaround is `const canvas = el("canvas") as HTMLCanvasElement` though.
> Return HTMLCanvasElement for el("canvas")

- index.d.ts
Added all non-deprecated, non-experimental HTML Elements from [the HTML spec](https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API) to HTMLElementOfStringLiteral.
Replaced deprecated HTMLTableHeaderCellElement with HTMLTableCellElement.
> Update HTMLElementOfStringLiteral to include all elements

- package.json
Typescript is giving an error when importing redom using `"moduleResolution": "Bundler"`. Defining specfic files in exports fixes this issue.
> fix typescript import using bundler module resolution

- index.d.ts
I'm in the process of reverse-engineering a project built using RE:DOM, and noticed they assumed the `mount` method always returns the child element passed, if said child is a `HTMLElement`. After reading through the RE:DOM source code, I confirmed that this assumption was correct.
I have added an overload to the `mount` method in the type definitions file.
> Add additional type definition for mount
